//
//  Extensions.swift
//  DeadLineTodo
//
//  Utility extensions for Date, TimeInterval, and formatting
//

import SwiftUI

// MARK: - Date Extensions

extension Date {
    
    /// 获取当天开始时间
    var startOfDay: Date {
        Calendar.current.startOfDay(for: self)
    }
    
    /// 获取本周开始时间（周一）
    var startOfWeek: Date {
        var calendar = Calendar.current
        calendar.firstWeekday = 2
        let components = calendar.dateComponents([.yearForWeekOfYear, .weekOfYear], from: self)
        return calendar.date(from: components) ?? self
    }
    
    /// 获取本月开始时间
    var startOfMonth: Date {
        let components = Calendar.current.dateComponents([.year, .month], from: self)
        return Calendar.current.date(from: components) ?? self
    }
    
    /// 获取明天开始时间
    var tomorrowStart: Date? {
        guard let tomorrow = Calendar.current.date(byAdding: .day, value: 1, to: self) else { return nil }
        return Calendar.current.startOfDay(for: tomorrow)
    }
    
    /// 格式化为年月日字符串
    func formatted(as format: String) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = format
        return formatter.string(from: self)
    }
    
    /// 本地化日期字符串
    var localizedDateString: String {
        formatted(as: NSLocalizedString("yyyy年MM月dd日", comment: ""))
    }
    
    /// 本地化日期字符串（无年份）
    var localizedDateStringWithoutYear: String {
        formatted(as: NSLocalizedString("MM月dd日", comment: ""))
    }
    
    /// 时间字符串 HH:mm
    var timeString: String {
        formatted(as: "HH:mm")
    }
    
    /// 获取指定年月的开始日期
    static func startOfMonth(year: Int, month: Int) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = 1
        return Calendar.current.date(from: components) ?? Date()
    }
    
    /// 获取指定年月的结束日期
    static func endOfMonth(year: Int, month: Int) -> Date {
        var components = DateComponents()
        components.month = 1
        let start = startOfMonth(year: year, month: month)
        guard let nextMonth = Calendar.current.date(byAdding: components, to: start),
              let lastDay = Calendar.current.date(byAdding: .day, value: -1, to: nextMonth) else {
            return start
        }
        return lastDay
    }
    
    /// 获取当月天数
    static var daysInCurrentMonth: Int {
        let calendar = Calendar.current
        let year = calendar.component(.year, from: Date())
        let month = calendar.component(.month, from: Date())
        let start = calendar.component(.day, from: startOfMonth(year: year, month: month))
        let end = calendar.component(.day, from: endOfMonth(year: year, month: month))
        return end - start + 1
    }
}

// MARK: - TimeInterval Extensions

extension TimeInterval {
    
    /// 分解为天、时、分、秒
    var decomposed: (days: Int, hours: Int, minutes: Int, seconds: Int) {
        let totalSeconds = Int(self)
        let days = totalSeconds / 86400
        let hours = (totalSeconds % 86400) / 3600
        let minutes = (totalSeconds % 3600) / 60
        let seconds = totalSeconds % 60
        return (days, hours, minutes, seconds)
    }
    
    /// 从天、时、分计算总秒数
    static func from(days: Int = 0, hours: Int = 0, minutes: Int = 0, seconds: Int = 0) -> TimeInterval {
        TimeInterval(days * 86400 + hours * 3600 + minutes * 60 + seconds)
    }
}

// MARK: - Color Helpers
// Note: Colors are auto-generated by Xcode from Assets.xcassets
// Use Color.myBlack, Color.blackBlue1, etc. directly

// MARK: - View Modifiers

struct TextContentStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .foregroundStyle(Color.myBlack)
            .multilineTextAlignment(.leading)
            .bold()
            .font(.system(size: 17))
    }
}

struct TextRepeatedTimesStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .foregroundStyle(Color.blackGray)
            .bold()
            .font(.system(size: 11))
    }
}

struct TextTimeStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .foregroundStyle(Color.blackGray)
            .padding(.bottom, 0.5)
            .padding(.horizontal, -3)
            .bold()
            .font(.system(size: 13))
    }
}

struct TextEndDateStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .foregroundStyle(Color.creamBrown)
            .padding(.bottom, 0.5)
            .padding(.horizontal, -3)
            .bold()
            .font(.system(size: 13))
    }
}

struct TextTitleStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .foregroundStyle(Color.blackGray)
            .bold()
            .padding(.horizontal, -2)
            .font(.system(size: 10))
    }
}

struct ImageIconStyle: ViewModifier {
    func body(content: Content) -> some View {
        content
            .padding(5)
            .bold()
            .font(.system(size: 20))
            .foregroundStyle(Color.blackBlue2)
    }
}

extension View {
    func textContentStyle() -> some View { modifier(TextContentStyle()) }
    func textRepeatedTimesStyle() -> some View { modifier(TextRepeatedTimesStyle()) }
    func textTimeStyle() -> some View { modifier(TextTimeStyle()) }
    func textEndDateStyle() -> some View { modifier(TextEndDateStyle()) }
    func textTitleStyle() -> some View { modifier(TextTitleStyle()) }
    func imageIconStyle() -> some View { modifier(ImageIconStyle()) }
}
